version: 2
jobs:
  build_docker:
    docker:
    - image: circleci/golang
    working_directory: /go/src/github.com/jakubkulhan/fcgipass
    steps:
    - checkout
    - setup_remote_docker
    - run:
        command: |
          docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          docker build -t jakubkulhan/fcgipass:latest .
          docker push jakubkulhan/fcgipass:latest

workflows:
  version: 2

  build:
    jobs:
    - build_docker
